apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-custom-cluster-role
  labels:
    rbac.example.com/aggregate-to-pod-list: "true"
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - list
