apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: myapp-service
spec:
  selector:
    app: solar-system
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
